### ISSUE TITLE
Another person with sound file issues. :)

### ISSUE THREAD

**Issue by MarkLannenUM** [Montana-Media-Arts/120_CreativeCoding#108]
I'm having an issue with a sound file. I've taken a screenshot of the code below where I declare the variable 'song,' define it in the preLoad function, and then in setup call it - song.play();

However, the song does not play, and when I inspect the element in Firefox, I get - TypeError: song is undefined which I don't understand as I think I have done that in the code.

Any suggestions welcome!

And yes, I have uncommented the p5 sound line in the html. :)
![git-screengrab](https://user-images.githubusercontent.com/31551434/39712726-50d622e4-51e1-11e8-94f0-3b6c1ba727c6.JPG)

**Comment by egriffin2** [comment]
Try restarting your server just to make sure the sketch is updating correctly from the code.  Also, you're using the preload function twice which is probably unnecessary.  Maybe try putting bgimg and song in the same preload function instead of having two of them.  I know this sounds simple but always double check the file name and type.  Also try getting rid of the "let song;" at the top, since you're defining the variable song in the preload function.  Hopefully some of that helps.

**Comment by MarkLannenUM** [comment]
Thank you! Not sure what the problem was, but I did all of those things and it is now working. 

:)
