### ISSUE TITLE
Issues with going live

### ISSUE THREAD

**Issue by erinflint** [Montana-Media-Arts/120_CreativeCoding#127]
So I'm not sure what exactly is happening but for some reason the initial link that I created in my "going live" section of this week's homework works but when I add the "hw-3/" part it gives me an error page?  The live link opens to last week's homework and, according to the "going live" page on the course website, it is supposed to open to an error page. No idea what I did wrong but any help is greatly appreciated!

**Comment by DVSnell** [comment]
I'm looking at your repository and I don't see the p5_lib folder, the index.html (which is the file your live site would look at), or even any previous assignment folders.

Your `sketch.js` file will only work when linked to an `index.html` file and referencing the files inside the p5_lib folder from the example.

Your `hw-3` should look similar to this:
![directorystructure](https://user-images.githubusercontent.com/39629030/45335405-75927d80-b53c-11e8-8bb5-801d8a9cb29b.png)
(The `images` folder is used in my readme.md and is not a requirement.)

This should be reflected on your GitHub Repositories.

**Comment by HagenNathaniel** [comment]
how difficult was this hw? looks like a few of you guys had some teething issues.
________________________________

**Comment by TNGlenn** [comment]
Hi I'm having a similar problem- my hw-3 looks like your screenshot DVsnell, but for some reason I'm not able to get it live. 

![screen](https://user-images.githubusercontent.com/42820201/45465821-2aab6e00-b6d4-11e8-9a33-04f08879058a.jpeg)

**Comment by Schrielle360** [comment]
I'm also having this issue. My files are all in line but nothing is working right its really annoying? Like I can't get it to load no matter what I keep getting the error

**Comment by TNGlenn** [comment]
I don't know how helpful this is, or what I initially did wrong, but my partner looked at my repository and we ended up deleting everything and starting from the beginning. Now all issues seem to be fixed. Not saying others should do this, but I'm guessing I at least messed something up when I was first setting up my repository (some major operator error I'm sure) and my partner helped me set it all up and it works.

**Comment by DVSnell** [comment]
Couple things to keep in mind for others who stumble on this issue:

* You only need to make one repository, which all your homework can live inside, each in their own subfolder.
* Naming is important.  If I name my base repository `Bananas_aRe_GrEAt` and my homework `DashFlance`, I have to use those EXACT names when linking to my repo and my live site, stupid capitalization and all.
* The hidden `.git` folder and `.gitattributes` file are required only in your base repository.  If they're in other folders or missing, things could break.  If you don't have them, use the `Create a Repository` options in GitHub Desktop.  Look for extras if you're having trouble committing and publishing, especially if GitHub Desktop keeps giving you an `Commit Failed - Exit Code 1`.  Basically, Git needs one set of Gits, but it doesn't like Gits in your Gits.
* Don't forget to use the `Settings` button in your repository on the GitHub website to make a repository into a live site.
* It might take some time to actually go live, even if the little link turns green and says you're good to go.  Github is used a LOT and there might be slow downs.
* Your browser might be displaying a previously stored version of the webpage in order to save you time and bandwidth.  Try clearing your browser cache if you keep getting 404s.
* Make sure your browser actually allows scripts to run.  This is usually stopped by security settings, anti-virus/malware or extensions/addons.
* Be Fearless.  Have FUN.  Computers are exceptionally resilient and there are very few things that can render one permanently inoperable.  If you're not sure if you should do something, Google it.  Far smarter (and dumber) people have probably tried and they probably have rants or stories about what happened. Don't be afraid to experiment (so long as there is no looming deadline).
* Save Often.  Make Backups.  Make Backups of Your Backups.  Get a Swiss Bank Account with a safety deposit box.  Send the Backups to the safety deposit box.  Leave clues around the world in famous works of art directing you to the safety deposit box in case you get amnesia after trying an "exotic" drink in the South Pacific.  Have a bittersweet but soulful connection in a Greek fishing village with...  have I said too much?  I've said too much.
* **Save Often.**  I mean it.

A couple is usually two, right?

I don't count well.
