### ISSUE TITLE
hw-3 Going Live

### ISSUE THREAD

**Issue by JoleneTiffanyG** [Montana-Media-Arts/120_CreativeCoding#129]
I keep getting the Error 404 message after committing my changes successfully and adding **hw-3** to the end of the url.   The **index.html** is in the right place and I can preview it and the color is right and the text is placed correctly.  My directories seem to be organized correctly

**Comment by JoleneTiffanyG** [comment]
More information:  I tried copying **index.html** directly into **hw-3** directory instead of having it live in the subdirectory **01-hello-world** which is inside of **hw-3** and contains the project, including **index.html**.  Now when I click on **index.html** inside of **hw-3** it opens to a blank page, but when I open the original still inside of the subdirectory **01_hello-world** it still opens up to the proper image.  I tried adding **/hw-3/01_hello-world** to the end of the url and it comes up with a blank page.  Adding just **/hw-3** to the url still returns the Error 404

**Comment by DVSnell** [comment]
If you throw another `/`at the end of `/hw-3`, in your address bar  does it work?

**Comment by JoleneTiffanyG** [comment]
Nah that was the first thing I tried :(

**Comment by JoleneTiffanyG** [comment]
When I originally was supposed to create an **index.html** file in the very beginning, how is that process supposed to go?  I added the file and gave it that name, but I just realized the icon beside it is not an html icon, and I'm wondering if it won't convert and is still a .txt?  Would that matter or is the source just the html code I wrote in Atom?  That part looks fine and shows up fine

**Comment by JoleneTiffanyG** [comment]
And now adding **hw-3** to the end of the url yields a blank page, no more Error 404

**Comment by DVSnell** [comment]
Might be making progress with that last bit.  Don't forget to put the`p5_lib` folder in the same folder as your `index.html` and `sketch.js` files.

**Comment by JoleneTiffanyG** [comment]
Yep they are all three inside `hw-3/01_hello-world`   When I click on `index.html` in the `01_hello-world` subdirectory inside of `hw-3` it brings me to the correct image

**Comment by erinflint** [comment]
I'm also getting the blank page when I add the hw-3.

**Comment by JoleneTiffanyG** [comment]
When you click `index.html` in your directory it pulls up the **Hello World** though yeah?

**Comment by erinflint** [comment]
Yup!

**Comment by HagenNathaniel** [comment]
So it's finding it,  but won't call it/find it when you check the file in github?

Sent from my Samsung device


-------- Original message --------

**Comment by JoleneTiffanyG** [comment]
Yeah that's what's happening to me anyway

**Comment by DVSnell** [comment]
Okay, so for others who may see this let's break down the GitHub live site a bit.

The formatting is:
Username
.
github
.
io
/
Repository name
/
Folder
/
Subfolders
/
Ad Nasuem.

So for example, my live site for hw-3 is `dvsnell.github.io/120-work/hw-3/`  but what the browser is actually seeing is `https://dvsnell.github.io/120-work/hw-3/index.html`  My username is `DVSnell`, my stuff is hosted on `github.io` and my repo is `120-work`.  My homework for week 3 is in `hw-3` and that folder contains my `index.html`.

After looking at your repository, yours would be `jolenetiffanyg.github.io/course-work/hw-3/01_hello-world/`.  Again, the `index.html` is implied.

A 404 means there is no index at all, but since yours is returning a blank page it means the browser can see it and display it.  Looking at your `index.html`, I can see everything is in order.  The `sketch.js` and `readme.md` is also good, but there is no copy of the `p5_lib` folder and subfiles in your repository.

So the index is there, the sketch has code, but the index can't display that code since the p5 files are missing.  Try putting the `p5_lib` folder with it's three child files from the original example or course-work inside your `01_hello-world` folder.  And don't forget to commit and push the changes to GitHub!

**Comment by DVSnell** [comment]
So, @erinflint I can't even see you `index.html`.  Don't forget to set the settings on your repository via the homework here: [Check the "Let GitHub know we want our repo to be a webpage" part](https://montana-media-arts.github.io/creative-coding-1/modules/week-3/hw-part-2/)

**Comment by JoleneTiffanyG** [comment]
![screenshot-p5folder](https://user-images.githubusercontent.com/42923897/45396937-09c31a00-b5fb-11e8-8841-860d68db5021.png)

So it looks like the `p5_lib` folder with its subfolders are showing in both **Atom** and **GitHub Desktop**, as well as when I look into the folder directory.  Am I missing something?

**Comment by DVSnell** [comment]
Yeah, you're good, but it's not on Github (the site).  The green + means the file(s) have changed, but haven't been committed or published.  Go ahead and make a commit, publish and let's see if that works.

I realize the language is a little clunky.  GitHub, GitHub Desktop, GitHub the site... It's a bit annoying.

**Comment by DVSnell** [comment]
![site shot](https://user-images.githubusercontent.com/39629030/45397264-7559b700-b5fc-11e8-9b02-47ea6d7b5375.png)

Like That.

**Comment by erinflint** [comment]
Yeah, I successfully committed everything but can't get the "HW-3" addition to work when I add it to the url.

**Comment by DVSnell** [comment]
Right, that's because your repository flow is `120-Work -> HW-3 -> empty-example`  so the last part of the URL should be `/empty-example`  Adding the `/hw-3` only works if the last step in your repository is `hw-3`.  Basically, `https://erinflint.github.io/120-work/HW-3/empty-example/hw-3/` points to a non-existent location.

The fault here is the instructions not taking into account the possibility of different repository structure and names.

All that being said, even with the index.html there, I can't access it outside the raw code on your repository.  Are you sure you've made the 120-work repository settings a Github Pages site?

**Comment by erinflint** [comment]
https://erinflint.github.io/120-Work/HW-3/empty-example/ this is the link that ended up working for me, thank you so much for your help. I was really overthinking it.

**Comment by DVSnell** [comment]
@erinflint Yep!  That one works perfectly.  If you want it to match Prof. Musick's you can basically move everything in `/empty-example/` back one step to `HW-3` and drop the last part of that URL you linked above, but if not, your Hello World is looking good!

**Comment by erinflint** [comment]
@DVSnell you are a life saver! Thank you so much. This issues forum is invaluable to someone such as myself who has never even looked at code before. Thanks!

**Comment by JoleneTiffanyG** [comment]
I have committed and published a million or so times with the `index.html` in the right place and working, and the `p5.lib` has been there the whole time.  So I'm not sure where the problem could be...  Right now though when I try to commit, I'm getting that *Commit failed. Exit code 1* message.  All I did is change something in my readme so I don't think it will affect the main problem I'm having, but do you remember what that error message is about?

**Comment by JoleneTiffanyG** [comment]
Ok the error message stopped happening on its own without me changing anything.. So I guess I'll worry about that next time it happens.  But it's still just blank when I navigate to **hw-3/01_hello-world** which is where my `index.html` lives and it works perfectly fine when I open it from the folder.  I've committed and pushed multiple times to make sure it's all current..

**Comment by DVSnell** [comment]
Yeah, look inside the `p5_lib` folder in Atom and delete the `.git` and `.gittattributes` items from there.  Exit code 1 tends to happen because there is a git inside another git.  After deleting them, commit and publish and it should work.

If not, you can manually add the files from the repository webpage.

**Comment by JoleneTiffanyG** [comment]
![hw-3-help](https://user-images.githubusercontent.com/42923897/45446829-1e4ef300-b68b-11e8-9919-87e7c1f4d6bc.png)

**Comment by JoleneTiffanyG** [comment]
Ok deleting the extra git. files again.  What do you mean by adding the files manually?

**Comment by DVSnell** [comment]
So, when you're looking at your repository on the github website, you can click through to the folder that has your working `index.html` and `sketch.js` and click the `Add Files` button on the right hand side.  Drag and drop the `p5_lib` folder from Windows Explorer into the designated space and put a commit comment at the bottom of the page before clicking submit. 

Make sure the `.git` and `.gitattributes` items are NOT in that folder.

**Comment by JoleneTiffanyG** [comment]
What, before I even had a chance to do what you said suddenly everything's alright!  But I hadn't changed anything.  Maybe for some reason it's just taking a super long time when I try to commit and push?  I'll keep that in mind and wait half an hour or so before I start losing my mind looking for mistakes.   Thank you so so much for your help, you are the best!!

**Comment by DVSnell** [comment]
In my experience, 7% of all negative computer interactions are resolved by magic, so that's what I'll chock this one up to.

**Comment by JoleneTiffanyG** [comment]
Hahaha mine have been resolved by magic like 30% of the time so far
