### ISSUE TITLE
Problems publishing to origin 

### ISSUE THREAD

**Issue by mprimeau1** [Montana-Media-Arts/120_CreativeCoding#141]
Hello, I am having a problem with hw4. I am trying to publish my files to origin on github desktop and when I do it always says error file to big. I've gone back and tried getting rid of excess files but still having the same error message. Anyone else having this problem? 

![help](https://user-images.githubusercontent.com/42810766/45772868-10a6e980-bc06-11e8-9f89-008a9bcc6c1f.png)

**Comment by mafordah** [comment]
It looks like it's asking you to remove a single file that is larger than 100MB. Is there anything in your repository that is larger than 100MB?

[This](https://github.community/t5/Support-Protips/Working-with-large-files-and-repositories/ba-p/9343) is the error on the github community page.

**Comment by mprimeau1** [comment]
Yeah I removed a bunch of files that were examples and tried reorganizing it but I can't seem to figure out what file it is that is even to large.

**Comment by mafordah** [comment]
100MB would have to be a pretty big file I think for what we're doing. Are there any videos or something like that that might've slipped into the directory? I didn't download the example files for this week so I'm not sure what was in them.

**Comment by DVSnell** [comment]
If you've manually removed the files, you'll probably have to cancel the attempted push before making another commit.  Running Git from a command line utility you can use `git merge --abort` and then try to commit and push again.

**Comment by mprimeau1** [comment]
What is git-merge and how do i use it?

**Comment by DVSnell** [comment]
That git-merge command forces GitHub to reset its changes and basically clear any inconsistencies between your online repository and the one on your computer.

So, if you haven't, you'll have to install Git.  Which might sound weird since we have GitHub Desktop.  Git itself allows you to use special commands beyond what GitHub Desktop provides.  You can find the installer for your chosen system here(https://git-scm.com/downloads) with simplified instructions here(https://git-scm.com/book/en/v2/Getting-Started-Installing-Git).  The second link is slightly outdated as GitHub Desktop for WIndows does NOT install PowerShell/Command Line interfaces.

After you've installed it, you can use Git Bash or Git CMD to navigate to where your repository is on your computer.  (Professor Musick went through some command line navigation for the Mac, but its pretty easy to just google instructions based on your Operating System)  While the command line is there, type in that `git merge --abort` in bash or the CMD and then you should be able to use the GitHub Desktop app like normal.

NOTE: You could probably delete your `.git` folder and `.gitattributes` files (you can see them in Atom) and remove your repository from GitHub Desktop which might achieve the same result.  But you'll need to set up your repository again like in Week 2, upload it and make it a live site.

**Comment by mprimeau1** [comment]
I created a new repository and moved all my old files into the new repository and it seemed to work. I also downloaded git which I should have done before. Everything seems to be working now.
