### ISSUE TITLE
Opening index.html showing nothing

### ISSUE THREAD

**Issue by lilyj521** [Montana-Media-Arts/120_CreativeCoding#143]
I'm working on this weeks p5 drawing project, but when i open my index.html its showing nothing even though I know the code I have in my sketch.js should work. My index.html file from last week in my hw-3 folder is working fine, I even tried copying the exact code from that sketch.js into the sketch.js in my hw-4 folder, but it shows up blank in the browser, even though it works perfectly in the hw-3 folder. Considering my hw-4 folder is literally a duplicated version of my hw-3 folder, I have no clue what could be causing this. It's just weird because the exact code that works using the index.html from my hw-3 folder does not work in my hw-4 folder. No matter how much I change the code, I can't get the browser to show anything but a blank screen.

**Comment by DVSnell** [comment]
Try clearing your browser cache and reloading.  I get:
![lilyh4](https://user-images.githubusercontent.com/39629030/45792698-29d28900-bc4c-11e8-8222-4de0cd73f12f.jpg)

**Comment by lilyj521** [comment]
@DVSnell Yeah, I ended up actually just deleting that folder and making a new one, so now it works fine. Thanks though!

**Comment by daylinscott** [comment]
@lilyj521 Hey I'm having this same problem now, I tried deleting my folder and making a new one but nothing seems to be working. Anyone have any tips?

**Comment by wattse13** [comment]
@daylinscott In your hw-4 Readme you wrote that you're getting a 404 error. I think there could be a couple of reasons for that. 

What does your URL look like? If you are trying to use your github web page it is important to add the hw-4 directory to the end of the address. For example your git hub web page URL should look like: 

https://yourusername.github.io/120-work/hw-4/ 

and not like: 

https://yourusername.github.io/120-work/

When I looked through your repo, I noticed that your hw-4 directory was inside of your coursework directory instead of directly in your 120_work directory. Both your hw-2 and hw-3 directories are in your 120_work directory. I don't know if moving your hw-4 directory will get rid of the error, but it's worth a try. 

And finally, when I looked at your hw-4 sketch.js I noticed that you are missing a lot of semi-colons in your code. Adding semi-colon's after all of your `fill();` and `ellipse();` functions might also help. 

I hope this helps or at least gives you a few places to start looking.
