### ISSUE TITLE
.DS store

### ISSUE THREAD

**Issue by daylinscott** [Montana-Media-Arts/120_CreativeCoding#144]
Every time I try to push something to GitHub this file "DS store" seems to piggyback along with it and I'm not sure how to get rid of it, is anyone else having this problem?

**Comment by DVSnell** [comment]
`.DS_Store` is a file created by the Apple MacOS and holds directory information and metadata about the folder it lives in.  It's safe to remove either in GitHub Desktop or on the github site.  Certain other files might piggyback across like video thumbnails and metadata containers.

Since it contains metadata that is updated whenever the folder or files in it are changed, it will appear in your changed files a lot.  To make GitHub ignore those forced changes, right click (or CMD+Click) on it in GitHub Desktop when it shows up and choose `Ignore this file`.

Be aware that this will make another hidden file in your repository called `.gitignore` which is just a list of files you've told GitHub Desktop not to track anymore.  You can always unignore files using GitHub Desktop.
 
If you try to delete`.DS_Store` in the local folder it lives in, the OS will just make another one the next time you open that folder.
