### ISSUE TITLE
Background in function setup or function draw 

### ISSUE THREAD

**Issue by chloeortega** [Montana-Media-Arts/120_CreativeCoding#149]
Salutations virtual acquaintances, ^-^

I'm currently working out the final touches on my hw-5 animation, I was wonder if there is a way to have both a shape following the mouse and essentially leaving a "trail" while at the same time have another shape moving while erasing every frame as it moves. 

I know to erase every frame as the object moves to declare the `background`  in the `function draw`, but then the shape following the mouse doesn't leave a "trail". 
When I declare the `background`  in the `function setup` the "trail" appears when I move my mouse, but the other object has a "trail" as well. 

Is there a way to have both?

**Comment by DVSnell** [comment]
I was investigating something similar and it's a bit advanced so I'll probably be working on it on my own time instead of for this project, but here's a video that explains a way to achieve the trailing effect:

https://www.youtube.com/watch?v=vqE8DMfOajk

It's pretty cool, regardless.

Also here's his end source code if you want to dissect it a bit:

https://github.com/CodingTrain/website/blob/master/Tutorials/P5JS/p5.js/09/9.07_p5.js_Drawing_Object_Trails/ES6_Version/sketch.js

**Comment by spkvfx** [comment]
This can be done without a lot of that script, it should even be able to be done all within the `draw()` function, even. 

At the basic core, what you need to do is write your trail into an array, and then remove the array element upon erasure using `split()`.

I do not think that arrays have been covered just yet, but if this is something you're interested in doing, it can certainly be done.

**Comment by chloeortega** [comment]
@DVSnell I was watching that video I'll probably try come back to it in the future, thank you!
@spkvfx  Thank you, I will look into the function you have suggested and read up on arrays in the book!

**Comment by spkvfx** [comment]
No problem. 

I'm currently stuck in an array purgatory myself!
