### ISSUE TITLE
not related to coding hw..

### ISSUE THREAD

**Issue by HagenNathaniel** [Montana-Media-Arts/120_CreativeCoding#155]
Having trouble getting my repo to work as a website in Web dev intro class..

you'd think I'd get this after 2 assignments here, lol!

Anywho, this is the link to get to the repo:

https://hagennathaniel.github.io/web-dev-hw/

and I need to get the 'Project-1' directory to work.

Also, I am not sure the image is working correctly, it's in the right folder as she wanted, but not sure it works right either...

Any assistance there would be greatly appreciated.

Thanks

**Comment by DVSnell** [comment]
For some random debugging, you have `<\h3>` instead of `</h3>` on line 15.

For the image, you'll need to use `"./images/ZZ_top.jpg"` as your source.  That `.` at the start of the string moves the directory up one level and then the rest of the string tells it which folder/file to access.

And as for making it live, have you set that repo to be a live site in your git settings?  That's the only thing I can think of off the top of my head.

**Comment by HagenNathaniel** [comment]
yeah, that link I posted was from the repo live site I set up...it's the "master" level of the entire course github repository.

and thanks for the random debug, I did it a bit fast.

**Comment by HagenNathaniel** [comment]
![ss1 2](https://user-images.githubusercontent.com/42828220/46181846-5f4b2800-c285-11e8-9955-aa60c6378a69.PNG)

**Comment by DVSnell** [comment]
Maybe the file naming convention is strict.  Try changing your index from `Index.HTML` to `index.html`  Otherwise, I can't see why it isn't working.  You need minor corrections on lines 42 (`</hr>`) and 43 ( `</pre`).  Github is fine.  I can even access the `readme.md`s for your other assignments in that class directly through the browser.  Hopefully it's just a naming convention thing.

**Comment by HagenNathaniel** [comment]
made the changes I could figure out, but still a 404...

New code, as well as repo location:
![ss 3](https://user-images.githubusercontent.com/42828220/46250434-02bc4a00-c3f8-11e8-9bb3-cd1574b987ad.PNG)
![ss 2](https://user-images.githubusercontent.com/42828220/46250435-02bc4a00-c3f8-11e8-89e3-ad1358955b97.PNG)

**Comment by HagenNathaniel** [comment]
almost thinking it's the way the link is set up..

doesn't make much sense though.

**Comment by HagenNathaniel** [comment]
the instructor found  the issues, thanks for trying guys!! :)

**Comment by DVSnell** [comment]
What were the issues?  I was able to run the site's code just fine locally.  Was it a Git problem?
