### ISSUE TITLE
When to use the modulo operation

### ISSUE THREAD

**Issue by mprimeau1** [Montana-Media-Arts/120_CreativeCoding#156]
Has anyone used the modulo operation yet in HW6? When should I use it in my var?

**Comment by HagenNathaniel** [comment]
haven't even started HW6...been so busy with my other classes....

I have no idea where to start, so maybe we can help each other out, LOL!!

anyway, a possibly useful answer to your question would be:

I think a good way to use it, since it is division with a remainder, is when you have a variable you want to use to draw a line or point or something in a new spot, and since it would most likely be variable, (especially with a random() number you generate) it would make for a VERY interesting result.

Provided it doesn't try to divide by zero, of course

**Comment by mafordah** [comment]
I used modulo to make a stroke color change over time as it moved. Dividing the frame count by 256 gave a remainder between 0 and 255 which was a good input for color that changed every frame.
```
noFill();
  colorChange = frameCount % 256;
  greyStroke = map(colorChange, 0, 255, w, b);
stroke(greyStroke);
  line(point.pos1X, point.pos1Y, point.pos2X, point.pos2Y);
```

**Comment by spkvfx** [comment]
It's probably my favorite operator! :) However, when I first learned about it I also was kind of wondering what the point was.

I've found that Modulo is useful any time you need to count to a certain point and start over, but using a constantly increasing reference - like a frame count or position. This is useful for anything that is periodic.

So, for example:

```
ellipse(x,y,w,h) ;
x++ ;
```

would result in the ellipse just running off screen forever … but with modulo:

```
ellipse(x % width,y,w,h) ;
x++ ;
```

it will get to the edge of the screen and then pop back over to 0 and start again. Conversely, if you move it the other way once it gets down to zero, it will pop back to the other edge of the canvas.

Modulo is great because you can also use it to trigger something to happen every Nth frame:

```
ellipse(x,y,w,h) ;
if (frameCount % 10 == 0) {
    x+=10 ;
}
```

This will move ellipse ten units on every tenth frame; or, on any nth frame of ten:

```
ellipse(x,y,w,h) ;
if (frameCount % 10 == 6) {
    x+=10 ;
}
```

This will cause it to shift on every 6th frame; So let's say you want it to move with some frequency no less than every 10th frame?

```
ellipse(x,y,w,h) ;
if (frameCount % 10 == random(0,10)) {
    x+=10 ;
}
```

using if/else you can get a flip-flop :

```
ellipse(x,y,w,h) ;
if (frameCount % 10 <= 5) {
    x++ ;
} else {
    x--  ;
```
This will cause the ellipse to go right one unit for 5 frames, and then left for 4 frames and then right again.

Modulo is very useful in a number of practical circumstances. The displacement shader I used in the house siding here is a simple modulo function along the local Y axis:

https://vimeo.com/279360206

Notice that it essentially produces a saw-tooth pattern. This prevents having to sample a ramp, so in theory, anyway, it is more efficient to use mod.

In another example, I used modulo with some variation to provide impulse velocity to the lava:

https://vimeo.com/185570968

**Comment by Codykrull** [comment]
I was a little lost on where to use modulo myself, and it's neat to see new ways to use the operation.
