### ISSUE TITLE
Problem with an if statment

### ISSUE THREAD

**Issue by wattse13** [Montana-Media-Arts/120_CreativeCoding#169]
Hello everyone,

I am currently having a problem with an if statement. [Here is a link to my code.](https://github.com/wattse13/120_work/blob/master/hw_8/sketch.js) And here is a link to the [live sketch](https://wattse13.github.io/120_work/hw_8/)

I am trying to code a simple game. The goal is to reach the left side of the screen without letting the square be hit by the falling ellipses. If the square runs into one of the falling ellipses, then the square is drawn back on the right side of the canvas. I did this using the `dist();` element and an `if(){}` statement which tested the statement: if the distance between the center of the rectangle and the center of an ellipse is less than 60 then evaluate as true. If when evaluated the statement was true, the square would be redrawn on the right side of the canvas. 

So far, this works for the first ellipse in the rectangles path. However, when the rectangle is hit by the 2nd 3rd and 4th ellipses, then nothing happens. I hope I was able to adequately describe my problem and any help would be greatly appreciated!
![screenshot 14](https://user-images.githubusercontent.com/42781660/47101476-69fb3c00-d1f7-11e8-95bc-c72565c33c45.png)
![screenshot 15](https://user-images.githubusercontent.com/42781660/47101483-6d8ec300-d1f7-11e8-9ed1-f855c892d434.png)
![screenshot 16](https://user-images.githubusercontent.com/42781660/47101488-71224a00-d1f7-11e8-983f-70762966c8ec.png)
![screenshot 17](https://user-images.githubusercontent.com/42781660/47101494-7384a400-d1f7-11e8-9189-74bd9ee84c44.png)

**Comment by spkvfx** [comment]
Hi. I'm not sure if you've found a solution yet, but I think the problem is that when you're testing the boulder position you're only accessing the original object, and not the specific object at a given location.

I think to do this properly you'll need in the least a boulder() function and perhaps more properly a boulder() class, which you would need to populate into an array.

I think the best way to accomplish this would be to check where Thomas is, then from that determine the distance from the corresponding boulder, that way you don't need to iterate through all the boulders when it's not going to be possible for a collision with any given boulder.

This is just my guess though, glancing over your code.

**Comment by wattse13** [comment]
@spkvfx Hey thanks for the comment. I haven't found a solution yet, but I'll be sure to try out your suggestions!
