### ISSUE TITLE
Not Showing Up

### ISSUE THREAD

**Issue by hayliesunshine** [Montana-Media-Arts/120_CreativeCoding#172]
![capture1](https://user-images.githubusercontent.com/42792278/47623246-b0447b00-dad4-11e8-9150-a7b9f64cba2a.JPG)
![capture2](https://user-images.githubusercontent.com/42792278/47623251-baff1000-dad4-11e8-94af-ecf807a5dfc2.JPG)

Hey guys, here is my code for this week's homework. The goal here is that I want white stars of random size and location to show up each frame, with one of the three quotes to show up each frame in the middle of the canvas, in light purple. However, all that is showing up is my black background, and I have NO idea why. Does anyone know why? Thanks!

**Comment by jballas** [comment]
@hayliesunshine Is the star function missing one of the parameters? I don't see any **npoints** on line 27.

```function star(x, y, radius1, radius2, npoints){}```

**Comment by hayliesunshine** [comment]
Oh my goodness, that was totally it. Thanks! I'm still not sure why my text isn't showing up, though.

**Comment by spkvfx** [comment]
Your random function is looking for a random number between quoteArray[0] and quoteArray[1]. I am not sure if/how it is using the third argument.

Because quoteArray is a list of strings there is no random value between them, so it is returning NaN (not a number).

To randomly select from a list, I think you need to use the array itself as the argument. It should work if instead: `random(quoteArray)`.

**Comment by hayliesunshine** [comment]
I made that change, and nothing happened, and then I changed it so that it said text(random[quoteArray]);, and that didn't work either. Any other suggestions?

**Comment by DVSnell** [comment]
Try using parenthesis instead of brackets.  So `text(random(quoteArray));` instead of `text(random[quoteArray]);`

Also, strings should use apostrophes instead of quotes so `var = quoteArray ['words 1', 'words 2', 'words3']` instead of `var = quoteArray ["words 1", "words 2", "words3"]`

Then `text(random(quoteArray));` will make `text('words1')` or `'words 2'` and so on.  This will display on screen as `words 1` or the other random values without quotes or apostrophes.

**Comment by spkvfx** [comment]
I think full quote marks should work fine (at least it does in other languages), but yes, the `text(random(quoteArray))` is correct.

The proper usage for an array is `array[index]` so what you're saying with random[quoteArray] is an array called random with an index of quoteArray - which isn't what you're wanting to say.

**Comment by DVSnell** [comment]
Yeah, full quotes do work fine, but since English uses them to denote dialogue in written text, I was taught the best practice of strings in apostrophes to cut down on escape characters.  

For example, using quotes to denote strings means you have to use `"\"Who's there?\" he called.  \"Show yourself!\""` while apostrophes mean you can put `'"Who\'s there?" he called.  "Show yourself!"'` which is a bit more "normal, standard English" readability-wise.  I did have one compatriot who just learned to always write dialogue with `\"` replacing the standard `"` though it did make his handwriting a bit complex so, your mileage may vary.

It is completely personal preference though since most modern programming languages are flexible with it and we have to worry about run time a bit less due to processing power increases.

Just make sure whatever you pick is consistent throughout your code.  I think that's the most important thing to readability in my opinion.

**Comment by hayliesunshine** [comment]
I tried with the parenthesis as well, but those aren't working either.

**Comment by DVSnell** [comment]
I plugged in your code and got the text to appear by removing your initial `translate` (Line 19) and instead plugging its values into the actual `text` line as their X and Y coordinates.  

Based on the screen shots, I changed Line 22 from `random ( quoteArray[0], quoteArray[1], quoteArray[2] );` to `text(random(quoteArray), width/2, height/2);`

`text` in P5 expects its position data to be inside it, so `text('things to be displayed' X, Y)` instead of using `translate`.

The stars are a whole 'nother thing, though.

**Comment by spkvfx** [comment]
> Yeah, full quotes do work fine, but since English uses them to denote dialogue in written text, I was taught the best practice of strings in apostrophes to cut down on escape characters.

That is an excellent point! I am largely self-taught, so I'm not always aware of the conventional ways of doing things.

**Comment by hayliesunshine** [comment]
I got it to work, thanks guys!
