### ISSUE TITLE
This.

### ISSUE THREAD

**Issue by MorganLong26** [Montana-Media-Arts/120_CreativeCoding#174]
Hello I am doing assignment 11 and my this. is not registering. Like the text is not turning blue showing that it is active. Does anyone know how to make the this. work?

**Comment by DVSnell** [comment]
Do you mean on the moodle page?  If you can't submit because it hasn't been opened up for you, it would probably be best to send an email to the Stephanie or Prof. Musick so they can let you in.  You can find their contact info [here](https://montana-media-arts.github.io/creative-coding-1/syllabus/#teaching-assistants-and-lab-assistants).

Otherwise, I think we'll need some more information on what exactly is happening to your code in order to help.

**Comment by MorganLong26** [comment]
Im not able to see my sketch live, and I think it is because of my line of code this. =x . The this. isn't turning another color to show it is registering the line of code, so I was wondering if I have to type it a certain way.
![screenshot](https://user-images.githubusercontent.com/42792412/48119946-e8af2c00-e22d-11e8-84ae-d2f9a2de36a8.JPG)

**Comment by DVSnell** [comment]
Well, one problem is that your array and your object (class) have the same name, `ball`.  If you change one throughout , like making the array `orbs` and the object `ball`, then that will fix the first problem.  That one change allowed for the canvas to be drawn and the background displayed.

Then I fixed some minor syntax errors on Line 35 (changed `nostroke` to `noStroke`) and Line 36 (changed `Fill` to `fill`)

Now I have three little purple orbs, bouncing around my canvas.

**Comment by DVSnell** [comment]
It should be noted that the color changes in text are based on the settings used in Atom and it's colorization packages.  Your screenshot has the same colors as my own.  `this.` is grey and its properties like `x` and `r` are red.

**Comment by MorganLong26** [comment]
Thank you it works now!
