### ISSUE TITLE
Adding a picture as a background image

### ISSUE THREAD

**Issue by mprimeau1** [Montana-Media-Arts/120_CreativeCoding#182]
Hello, I have been working on this weeks hw, and I was thinking it would be cool to put a picture for my background image. I have been trying to use a jpg image and set the background to the size of the image, but still nothing. Any ideas? Thanks!

**Comment by JoleneTiffanyG** [comment]
Do you have a picture of your code?  Next week's content looks like we'll be going over putting in things like images so the course content might be helpful if you were unable to troubleshoot by googling the problem

**Comment by mprimeau1** [comment]
here is my code as it stands, but I would like have four different background images on a loop, but lets just start with loading one.  
![help1](https://user-images.githubusercontent.com/42810766/49050770-299dbf00-f1a2-11e8-89d3-cb12b4bbd9ad.png)

**Comment by mafordah** [comment]
It looks like you're using Chrome. For some reason, Chrome blocks images when you preview the code. I had the same problem. It's annoying, but the easiest way to get around it is to just preview your code in Internet Explorer, Edge or Firefox if you have it. After you commit it, it works just fine in Chrome. It just blocks taking images directly from the desktop for 'security issues'. I think you can preview it in Chrome, but you have to do it manually with a line of text enabling it access. I didn't bother because my code opened right up in another browser. 

If if keeps loading forever and your error says:

"Access to image at '_where ever your file is located_' from origin 'null' has been blocked by CORS policy: The response is invalid. "

Chrome is your problem.
