### ISSUE TITLE
Any ideads on what I'm doing wrong with final?

### ISSUE THREAD

**Issue by mprimeau1** [Montana-Media-Arts/120_CreativeCoding#189]
So basically  have four images that I would like to animate. I was able to display one image a a time, but once I started trying to animate everything disapeared.  Anyone have any insite to where my error is? Heres a few pictures of my code.

![help2](https://user-images.githubusercontent.com/42810766/49162783-e13ce900-f2e8-11e8-80c7-72f555aeb406.png)
![help3](https://user-images.githubusercontent.com/42810766/49162785-e13ce900-f2e8-11e8-9930-f3d09a30c8a3.png)
![help4](https://user-images.githubusercontent.com/42810766/49162786-e13ce900-f2e8-11e8-9469-596d3735d771.png)

**Comment by mafordah** [comment]
So I'm not going to be super helpful because I don't know exactly how to fix your problem (yet), but I do think the method of animating sprites that we were taught, with the sub rectangle, only works when everything is one image. If you have Photoshop handy, you can just edit your photos in to one and use that method. Or....

[This video](https://www.youtube.com/watch?v=DPFJROWdkQ8&vl=en) may have what you need. Shiffman is using Processing which is a little different, but I've been able to apply it to p5 by pretty much just changing `void` to `function` and `int` to `let`. 

I hope this helps!

**Comment by spkvfx** [comment]
Please post a link to your actual code and I will take a look at it. Otherwise, what is your console saying?
