### ISSUE TITLE
My image will not display 

### ISSUE THREAD

**Issue by Schrielle360** [Montana-Media-Arts/120_CreativeCoding#191]
As you can see, in my index file. My image will not under any circumstances display for my final project. I was wondering if anyone else is working with images and understands what the heck this error means or what? I am at a loss. 
https://i.gyazo.com/02e314cf4cea32699e5b4bc9ade69a72.png

**Comment by mafordah** [comment]
I had the same problem! Are you using Google Chrome? Google Chrome won't access images on your desktop for "security reasons". Try opening it in a different browser if you have one, and it should show up. It works on Google Chrome after you commit it but not when you open it directly from your desktop. It's annoying, but if you have another browser, it's a quick fix.

I think there's a way to open it manually by typing in a phrase, but I didn't look much into it since it worked when I opened it in Microsoft Edge.

**Comment by spkvfx** [comment]
I recently happened across something about this while looking into something else. They suggested running the code from a web server, so try running it from github, maybe?

**Comment by mafordah** [comment]
It should work when you run it from github. At least mine does...

**Comment by spkvfx** [comment]
Yeah, and I noticed last night that the p5 image docs actually disclose that it must be run from a server. I think it's some kind of security measure of sorts.

**Comment by Schrielle360** [comment]
Thanks for the help!
