### ISSUE TITLE
Still having trouble 

### ISSUE THREAD

**Issue by Schrielle360** [Montana-Media-Arts/120_CreativeCoding#203]
So. I have updated my code to have better formatting and everything. Still getting an error. Still can not get it to display. Anyone got a clue what I am doing wrong? Help needed I am clearly not as good at this as I thought I was lol. 

update: WOOO it displays. However, it is ignoring the edgeCheck function and chibiCheck function. How do I fix this?

**Comment by spkvfx** [comment]
Hi!

There are a couple of issues, but you're definitely on the right path. First, you have a misplaced bracket in the edgecheck() method. The method should be formatted:

```
  edgeCheck() {
      // check if the Chibi has hit a vertical wall (left or right walls)
      if (this.x + this.rad >= width || this.x - this.rad <= 0) {
          console.log("edge");
          this.deltaX *= -1;
      }
      // check if the Chibi has hit a horizontal wall (top or bottom walls)
      if (this.y + this.rad >= height || this.y - this.rad <= 0) {
          this.deltaY *= -1;
      }
  }
```

But the underlying problem here is that size is undefined, so you're trying to divide `undefined` by two, which results in `NaN`. Because this isn't a number, the result of your condition cannot be met.

Unfortunately Javascript is stupid and, unlike every otehr language on the planet, won't tell you when this happens. So the easiest way to diagnose this is to use `console.log()` and place it before and after statements. 

Once I figured out the if statement condition wasn't being met, I used `log.console()` again to check the terms: `this.x`, `this.y`, `this.rad`. Once I confirmed that `this.x` and `this.y` was accurate, I noticed that `this.rad` was returning `NaN`. At that point I was able to diagnose the problem.

There is a debugger built into the web browser, but i don't know how to use it, and for little things that are limited in scope like this I'd rather just print to the console anyway.

**Comment by spkvfx** [comment]
Oh, and you do have a zero distance condition which will cause Chiblis to pile up on creation. I had something similar to this in my project. In your case, simply waiting to call chibiCheck() after a few frames should work.

**Comment by Schrielle360** [comment]
@spkvfx Thank you so much. I keep making these small mistakes so its hard for me to notice.

**Comment by spkvfx** [comment]
That one was pretty difficult to spot, tbh. Like I mentioned, Javascript won't tell you if you're trying to do something stupid with a value. It'll just go ahead and try to add 6 to potato.

**Comment by Schrielle360** [comment]
@spkvfx I seriously would not have gotten it without you so I appreciate you taking the time To spot it. Can I ask you another question? My mousepressed function is not working no matter what I do. I am not sure how to fix that either. Any ideas?

**Comment by spkvfx** [comment]
Looks like a simple typo. You just need to change `if (d < this.r)` to `if (d < this.rad)` in the mouseCheck() method of Chibi.

**Comment by Schrielle360** [comment]
... I feel silly. Thank you again.

**Comment by spkvfx** [comment]
No need. 

I literally spent 6 hours chasing a mis-placed bracket on one of my assignments. Turned the whole thing upside down and couldn't figure it out.

**Comment by Schrielle360** [comment]
I have done that as well ha ha. Coding is so much fun.

**Comment by Schrielle360** [comment]
Would you happen to know how to code in a score board so every time my mousePress deletes a chibi it goes up by one? I know its text but I don't know how to make the score board go up with the mousepressed function XD

**Comment by spkvfx** [comment]
Fun begins when you can't figure something out, wake up at 2am, jot down some psuedo code for Monday but find yourself in the office at 3:30 on Saturday morning in front of your workstation thinking "let me fix this one thing... then I'll go home". 

... or so I hear.

Should just be a matter of incrementing a global variable inside mousePressed and using it as the text source.
