### ISSUE TITLE
Questions about adding sounds and button making

### ISSUE THREAD

**Issue by mprimeau1** [Montana-Media-Arts/120_CreativeCoding#208]
So what I'm trying to do is when you click on a certain object a a sound will play then when you click it again it will stop playing.  I have gotten my sketch to a point where I like how it looks, but when I started trying to make objects buttons then make them play sound it just can't seem to work.  The first object I am working on is my frog.  Here is an image of my preload function then what i have in my frog function. Any ideas on what I should do? 
![help5](https://user-images.githubusercontent.com/42810766/49703458-86e23900-fbc2-11e8-96f1-b3a575ad6276.png)
![help6](https://user-images.githubusercontent.com/42810766/49703459-86e23900-fbc2-11e8-9f96-2fc08ad898c7.png)
![help7](https://user-images.githubusercontent.com/42810766/49703460-877acf80-fbc2-11e8-8653-bafe647d0fe7.png)

**Comment by wattse13** [comment]
Hey @mprimeau1 I think you will have to add some object awareness if you want a mouse click on your frog object to trigger music. To do this, I would suggest using variables -- like frogPosX, frogPosY, frogR for the frog's body ellipse's x, y, and r, values -- the `dist();` function and an if loop. 

So, on lines 178 through 180, you have three different ellipses which I am assuming are used for the frog's body. In whichever ellipse is being used for the frog's main body, I would replace the numerical values with variables that have assigned numerical values. For example, if the ellipse on line 179 is the frog's main body instead of writing what you currently have you would write: 

`ellipse(frogPosX, frogPosY, frogR);` 

Then in another place in your code you could assign these variables the desired numerical values. After that I would look at your frog function. At the moment there is only the line: 

`if(this.clicked == true){play.soundFrog}`

It's hard to see what this.clicked does as I don't see it anywhere else in the pictures you provided. But, I might change the frog function to check for intersection before it plays the sound bit. This could be done by starting the function with a nested if statement:

`if(mouseIsClicked){

     let d = dist( frogPosX, frogPosY, mouseX, mouseY )

          if( d < frogR ){

               play.soundFrog

          }

     }`

The first if loop checks if the mouse is clicked or not. If it evaluates to true then the program runs through the next two lines of code. The variable 'd' is assigned the value of the distance between the mouse cursor position and the frogPosX and frogPosY location. The second if loop tests if the value of the variable d, or the distance between cursor and frog, is less than the value of the frog's radius, frogR. If the second if loop evaluates to true, then the sound bit is played.

I haven't worked with sound in p5.js so I'm assuming the play.soundFrog is the correct way of signalling to the program that a sound file should be played. 

Does this help at all?

**Comment by mprimeau1** [comment]
My code still isn't running properly but you did help thanks. Now I'm having a bunch of reference errors appear.  Especially with my preload function, with the music I'm trying to load (does not like that).

**Comment by egriffin2** [comment]
Hey Mary, I looked through your code screenshots and I don't see a .play function for any of the sound files you've loaded.  Once you load an mp3 with "loadSound" you have to give the computer the command to actually play the sound file.  Eli was definitely on the right track!  You're going to need to call the variable name and then ".play" so for example:
soundWater.play(); will need to be in your setup function after you've loaded your sounds in the preload function.  I believe you will need a play function for every one of your loaded mp3 files.

**Comment by mprimeau1** [comment]
So here's what I've been working on basically as soon as I start mixing music into here my preload wont preload the music but it will for images.  Heres a few pics of what I have been working on. I made a new function for if mouse is clicked and lots of this. statements in the classes.
![help5](https://user-images.githubusercontent.com/42810766/49757795-83aa8400-fc7a-11e8-9af7-1783da59b52b.png)
![help6](https://user-images.githubusercontent.com/42810766/49757796-84431a80-fc7a-11e8-866e-42c95b0b35b0.png)

**Comment by egriffin2** [comment]
I'd really recommend that you come in and talk to Michael.  It looks like you're loading lots of files so it might be best to have someone look at it in person.  I can tell you from looking at the screenshots there's a possibility that you're playing your files wrong.  Try the other way around: soundWater.play();
