### ISSUE TITLE
Image didn't populate in .md file

### ISSUE THREAD

**Issue by christinebmartin** [Montana-Media-Arts/120_CreativeCoding#214]
My .md file looks exactly as I expected, however my image is not appearing.  I used:
![Image of my editor](D:\Univ of Montana\120-work\hw-2\HW-2_Editor.png)

Here's the address for the file: D:\Univ of Montana\120-work\hw-2

Is it not coming through because of the space in "Univ of Montana"?

**Comment by ECPina** [comment]
We’re you able to fix it? I think your right about the spaces. Also, sometimes it’s easiest to create an image folder within your main directory (your HW-2 folder) and then place your image there. Then when you link to it, it would look like: 

! [Image of my editor] (./images/HW-2_Editor.png)

But make sure to take out the spaces. Hope that helps!

**Comment by ascha19** [comment]
Hello, Christine! i had the same issue with my image, and you're correct about the spaces. Either remove the spaces in "Univ of Montana" or replace them with dashes (ex. "Univ-of-Montana"; this is what I did with mine) and it should work.

**Comment by christinebmartin** [comment]
replaced spaces with dashes, still not showing.  I'm on a mission to make this work!

**Comment by ascha19** [comment]
Try writing the code a different way, perhaps? In this case, instead of "![Image of my editor](D:\Univ of Montana\120-work\hw-2\HW-2_Editor.png)" put "! [Image of my editor] (HW-2_Editor.png)" without the extra spaces, of course. Instead of the entire address, only put the name of the file in the parenthesis. When I posted mine, I didn't put the entire address but rather just the name of the file, which is what you're supposed to do, I believe. (Mine is ! [Image of my editor] (Second-Week-Screenshot.jpg" without those extra spaces again.)

Edit: Yup, it's most likely that because I just created those links on accident and had to edit them so you could see what I wrote. <'D

**Comment by christinebmartin** [comment]
Well, I ended up saving the file to my UMT box, I changed it from embedding an image to a link to the file in my Box and....VOILA!!!!
Thanks for everyones input! Closing this bad boy out

**Comment by Thatstickysmell** [comment]
@aschave19 thanks for the tip. totally worked for me. Just doing hm-2/image-name
