### ISSUE TITLE
hyperlink?

### ISSUE THREAD

**Issue by Franklinsamson** [Montana-Media-Arts/120_CreativeCoding#96]

**Comment by Franklinsamson** [comment]
Hey fellow classmates.. Im sorry to bring this up but professor is getting on me because I haven't been hyperlinking the read.me and the hw assignments.. please help me address this issue.. it would be greatly appreciated

**Comment by alexk2313** [comment]
When you go to the submission page on moodle, instead of just copying and pasting the links, click on the use advanced editor link under the character box. Then once you are on the advanced editor page, click on the down arrow under the character box. there should be a button that looks like a chain link. Type your desired word in the character box then highlight it and click the chain link button. You should be able to put the url there and specify if you would like to make it open in a new window. Hope this helps :)

**Comment by Franklinsamson** [comment]
thx alexk2313 

That did the trick.. thank you!!
